In [5]:
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.bincount(np.arange(5))

array([1, 1, 1, 1, 1], dtype=int32)

In [16]:
np.bincount(np.array([0,1,2,3,4]))

array([1, 1, 1, 1, 1], dtype=int32)

In [14]:
np.bincount([0,1,2,3,4])

array([1, 1, 1, 1, 1], dtype=int32)

In [10]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1], dtype=int32)

In [21]:
np.bincount(['a', 'b','c','c','d','e'])

ValueError: invalid literal for int() with base 10: 'a'